apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: cluster-issuers
  namespace: flux-system
spec:
  wait: true
  dependsOn:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSet
      name: cert-manager
      namespace: flux-system
      ready: true
      readyExpr: "status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')"
  resources:
    - apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: self-signed
      spec:
        selfSigned: { }
