name: test

on:
  pull_request:
  push:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@06ed49dcd3f3ce2fc8d1988848245873a91550bc #v2.7.4
      - name: Setup Flux Operator CLI
        uses: controlplaneio-fluxcd/flux-operator/actions/setup@7c1371546f1fc3dcd039d4b19bd8a97491947edb #v0.34.0
      - run: make up
      - run: make sync
      - run: make ls
      - run: make down
